name = "FewBodyPhysics"
uuid = "dd57e2ab-7dae-448b-a136-57ab9eca4234"
authors = ["Martin Mikkelsen"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
